import { BTN } from "../../constants";
import { ButtonNames } from "../types";

export const buttonsEn: ButtonNames = {
  [BTN.CallStart]: "/start",
  [BTN.Beginning]: "Let's Get it Started!",
  [BTN.Im_Smoking]: "I’m having a smoke 🚬",
  [BTN.Reset_Stage_1]: "Full Reset 👍",
  [BTN.Reset_Stage_2]: "Stage 1 Progress Reset 🐯",
  [BTN.Reset_Ignore]: "Keep it as it is ❌️",
  [BTN.Level_Easy]: "Training Mode 📚",
  [BTN.Level_Medium]: "Normal 👍",
  [BTN.Level_Hard]: "Advanced 👑",
  [BTN.Ignore_Success]: "I quit smoking!",
  [BTN.Ignore_Failed]: "I’ll keep smoking 👎",
  [BTN.Ignore_Busy]: "Let’s continue ▶️",
  [BTN.Ignore_Penalty_10]: "Make 10 penalty 🚀",
  [BTN.Local_Time_Correct]: "Correct ✅",
  [BTN.Local_Time_Wrong]: "✏️ Edit",
  [BTN.Local_Time_Plus_1]: "+ 1 hour",
  [BTN.Local_Time_Minus_1]: "- 1 hour",
  [BTN.Local_Time_Plus_30]: "+ 30 minutes",
  [BTN.Local_Time_Minus_30]: "- 30 minutes",
  [BTN.Local_Time_Confirmed]: "The time is correct 👍",
  [BTN.Local_Time_AmPm]: "AM/PM",
  [BTN.Local_Time_24h]: "24h",
  [BTN.Lang_RU]: "RU 🇷🇺",
  [BTN.Lang_EN]: "EN 🇬🇧",
  [BTN.Dev_Content_RU]: "RU 🇷🇺",
  [BTN.Dev_Content_EN]: "EN 🇬🇧",
  [BTN.Dev_Delete_User]: "Delete user 🗑️",
  [BTN.Dev_To_Stage_1]: "Reset to Stage 1 🗯️",
  [BTN.Dev_Fill_Stage_1]: "Fill Stage 1 📈",
  [BTN.Dev_Last_Time_1_Hour]: "Last Time to 1 hour ago 🕘",
  [BTN.Dev_Stage_1_More_Max]: "Stage 1 more than max 🕧",
  [BTN.Dev_To_Idle]: "To idle mode 💤",
  [BTN.Dev_To_Idle_Empty]: "To idle EMPTY 💤",
  [BTN.Dev_To_Idle_Three_Times]: "Idle + 2 pen days before 💤",
  [BTN.Dev_To_Idle_Max_Limit]: "Idle & MAX delta 💤",
  [BTN.Dev_Next]: "By timer ⏰️",
  [BTN.Dev_Motivizer_25]: "Motivizer to 25 ⛹️",
  [BTN.Dev_Motivizer_Full]: "Motivizer full ⛹️",
  [BTN.Dev_Ignore]: "To Ignore Mode 🌀",
  [BTN.Dev_Content]: "Content 📋",
  [BTN.Dev_Content_All]: "All Content 📋",
  [BTN.Recommendations]: "Recommendations",
};