export enum Content {
  MESSAGE = "MESSAGE",
  USER_UNKNOWN = "user_unknown",
  START_NEW = "start_new_user",
  START_EXISTING = "start_existing_user",
  START_EXISTING_STAGE_1 = "start_existing_stage_1",
  START_RESET_IGNORE = "start_reset_ignore",
  START_RESET_TO_STAGE_1 = "start_reset_stage_1",
  START_RESET_TO_STAGE_2 = "start_reset_stage_2",
  LANG = "lang",
  LANG_APPLIED = "lang_applied",
  FIRST_STEP = "1st_step",
  STAGE_1 = "stage_1",
  STAGE_1_IGNORE_MIN = "stage_1_ignore_min",
  STAGE_1_IGNORE_MAX = "stage_1_ignore_max",
  STAGE_1_PROCESSING = "stage_1_processing",
  STAGE_1_END = "stage_1_end",
  STAGE_2 = "stage_2",
  // TEST
  DEV = "dev",
  DEV_OFF = "dev_off",
}