export const youcanEn = [
  "You can decide for yourself when to smoke and when not to.",
  "You must overcome your habits. It’s not hard.",
  "You can skip an unnecessary smoke break.",
  "You’re doing this for your loved ones. And for yourself, first and foremost.",
  "You haven’t smoked SINCE you started using the bot.",
  "You don’t have to finish the cigarette if you don’t feel like it.",
  "The smoking schedule is just a timer. If you don’t feel like smoking yet, don’t.",
  "In reality, the desire to smoke doesn’t last long. Just 5–10 minutes.",
  "Waiting and dealing with stress is normal. Doing it without cigarettes is normal too.",
  "We’ve all been deceived by advertising. It’s time to let go of that. Quit.",
  "Only by working on ourselves do we reach new heights. You’re quitting—be proud of it!",
  "Imagine how surprised people around you will be when you quit.",
  "A piece of leaf wrapped in paper controls a person? No!",
  "Limit yourself every day. That’s the only way to overcome smoking.",
  "Many quit smoking only after facing the consequences.",
  "Once you decide when to smoke, not your habit, you’re no longer its slave.",
  "Smoking doesn’t calm your nerves. It’s just a marketing trick.",
  "Don’t give in until the very end. Not on holidays, not on hard days.",
  "Always remember—quitting smoking is your personal goal. You’re almost there.",
  "Feel like smoking? Set a timer for 10 minutes. You won’t want to—tested and true.",
  "So much money goes up in smoke…",
  "When you started using the bot, you firmly decided to quit smoking. Quit. It’s worth it.",
  "Bad habits are for people weak in spirit. That’s not about you.",
  "Track your progress using the bot. See how much has changed for you in a month.",
  "Most people are non-smokers. Quit.",
  "Smoking is an illusion of relaxation. In reality, your body suffers from its toxins.",
  "Visualize the negative. Remember what annoys you the most about smoking.",
  "You deserve better. Don’t smoke.",
  "This world is built on human lives but sustained by human achievements.",
  "You’re quitting smoking! You’re doing an amazing job!",
  "The determination to fight bad habits defines the modern person.",
  "Why break the smoking schedule if you’ll forget you wanted to smoke in 5 minutes?",
  "How hard it can be sometimes to wait for the next smoke break...",
  "A strange and useless habit shapes your free time?",
  "Others will look up to you as an example when you quit.",
  "Smoking is a system where the person always loses.",
  "Willpower is like a muscle in the gym. Beat smoking, and you’ll conquer other challenges too.",
  "When you exhale smoke, nothing remains. It’s just wasted time.",
  "Nicotinic addiction is a very, very tricky enemy. Fight it.",
  "If you feel like smoking, try thinking about something else. It might help.",
  "A cigarette isn’t your master! If you want to smoke, you will; if you don’t, you won’t!",
  "Why smoke if you simply don’t feel like it?",
  "Don’t give up. A month or two, and you won’t smoke. It’s simple.",
  "Check your stats occasionally. It’s shocking how much money went up in smoke! Command: /stats",
  "What could you do instead of taking another smoke break?",
  "You are no longer an asset to the tobacco company.",
  "Your body doesn’t die without nicotine; it’s just your brain trying to play its old trick on you.",
  "Every time you delay smoking, the addiction loses its power.",
  "Smoking is nothing but toxins and zero benefits.",
  "When you decided to quit smoking, you protected your future.",
  "Smoking only ruins everything. It’s a useless habit.",
  "What kind of chains decide that you need to inhale smoke?",
  "Think about how many people have been deceived by cigarette advertising.",
  "You are better and stronger than a silly habit.",
  "Quitting smoking is easier than most people think.",
  "Living around an object that not only gives you nothing but also harms your health.",
  "Cigarettes destroy health.",
  "The desire to smoke is a weakness.",
  "Why should a habit dictate your schedule? Quit!",
  "Smoking is something that should be left behind.",
].map(content => `🌟 🌟 🌟 🌟 🌟\n_${content}_`);
