name: deploy-to-ec2
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Run build task
        run: npm run build
      - name: Install production dependencies
        run: npm ci --only=production
      - name: Prepare deployment package
        run: |
          cp -r node_modules dist/
          cp package.json dist/
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "dist/"
          ARGS: "-rlgoDzvc -i --delete"
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DIR_NAME }}